# @staticimports
#   walk is_string cat0


#' Statically import objects
#'
#' @description
#'
#' This finds staticimports declarations, which are comment blocks that look
#' like this:
#'
#' ```
#' # @staticimports map map_chr map_lgl os_name any_named any_unnamed
#' # all_named all_unnamed
#' ```
#' It statically imports the named objects into a file, by default
#' `R/staticimports.R`.
#'
#' @param dir A directory
#' @param outfile File to write to. Defaults to R/staticimports.R in the
#'   current project. Use `stdout()` to output to console.
#' @param source A directory containing source files, or an environment to use
#'   as the source.
#'
#' @export
import <- function(
  dir     = here::here("R/"),
  outfile = here::here("R/staticimports.R"),
  source  = system.file("R", package = "staticimports"))
{
  names <- find_staticimports(dir)
  import_objs(names, outfile, source)
}


#' Statically import specific objects
#'
#' @inheritParams import
#' @param names A character vector of names of objects to import.
#'
#' @examples
#' if (interactive()) {
#' # Import `os_name` and `walk` into your project
#' import_objs(c("os_name", "walk"))
#' }
#'
#' # Write to stdout instead of R/staticimports.R
#' import_objs(c("os_name", "walk"), stdout())
#' @export
import_objs <- function(
  names,
  outfile = here::here("R/staticimports.R"),
  source  = system.file("R", package = "staticimports"))
{
  if (is.environment(source)) {
    env <- source
  } else {
    env <- new.env()
    files <- dir(source, pattern = "\\.[r|R]$", full.names = TRUE)
    for (file in files) {
      source(file, local = env)
    }
  }

  dep_table <- find_internal_deps(env)
  all_dep_names <- c(names, unlist(dep_table[names], recursive = FALSE, use.names = FALSE))
  all_dep_names <- sort(unique(all_dep_names))

  all_dep_objs <- mget(all_dep_names, env)

  # Get the source text for a function.
  get_src_text <- function(obj, name) {
    srcref <- attr(obj, "srcref")
    if (is.null(srcref)) {
      if (is.function(obj)) {
        message(
          "Note: can't get srcref for `", name,
          "`. Package should be installed with source refs. Using `deparse()` instead."
        )
      }
      return(deparse(obj))
      # return("NULL  # Note: no srcref was available for this object")
    }
    as.character(srcref)
  }

  # Given a list of functions (with source refs), write the source to a file.
  write_deps <- function(fns, outfile) {
    if (is_string(outfile)) message("Writing to ", outfile)

    cat("# Generated by staticimports; do not edit by hand.\n", file = outfile)

    for (i in seq_along(fns)) {
      fn_name <- names(fns)[i]
      cat0(
        "\n",
        # Ensure that names with weird characters, like %||%, get backticks,
        # like `%||%`.
        capture.output(print(as.symbol(fn_name))),
        " <- ",
        paste0(get_src_text(fns[[i]], fn_name), collapse = "\n"),
        "\n",
        file = outfile,
        append = TRUE
      )
    }
  }

  write_deps(all_dep_objs, outfile)
}



#' Find any static imports in the comments of the R/ directory
#'
#' This finds staticimports declarations, which are comment blocks that look
#' like:
#'
#' ```
#' # @staticimports map map_chr map_lgl os_name any_named any_unnamed
#' # all_named all_unnamed
#' ```
#'
#' @param dir A directory to look in. Defaults to
#'
#' @return A character vector of declared static imports.
#'
#' @export
find_staticimports <- function(dir = here::here("R/")) {
  files <- dir(dir, pattern = "\\.[r|R]$", full.names = TRUE)

  lines <- unlist(lapply(files, function(file) {
    text <- readLines(file)
    match_lines <- grep("^#\\s+@staticimports", text)
    if (!any(match_lines)) {
      return(NULL)
    }

    staticimports_line_idx <- integer()

    # Find any lines after this that start with #
    comment_start_lines <-  grep("^#", text)
    for (i in match_lines) {
      j <- i
      while (j %in% comment_start_lines) {
        staticimports_line_idx[[length(staticimports_line_idx) + 1]] <- j
        j <- j + 1
      }
    }

    # staticimports_line_idx

    match_lines_text <- text[staticimports_line_idx]
  }))

  lines <- sub("^#\\s+@staticimports", "", lines)
  lines <- sub("^#", "", lines)
  names <- unique(unlist(strsplit(lines, " +")))
  names <- setdiff(names, "")

  names
}
