# Generated by staticimports; do not edit by hand.

cat0 <- function(..., sep = "") {
  cat(..., sep = sep)
}

is_string <- function(x) {
  is.character(x) && length(x) == 1 && !is.na(x)
}

walk <- function(.x, .f, ...) {
  for (i in seq_along(.x)) {
    .f(.x[[i]], ...)
  }
  NULL
}
